### ISSUE TITLE
UAVCAN v1 migration

### ISSUE THREAD

**Issue by davidlenfesty** [UofA-SPEAR/software#239]
This is a tracking issue for the UAVCAN v1 migration.

Unfortunately 20.04 support on the TX2 looks a ways off and migrating to Python3 isn't really worth the effort, so instead of re-vamping @jo12bar 's mapper node in Python for now I'll be writing a vaguely equivalent node in C++. Hopefully when we move to Noetic/ROS 2 we'll pick back up with Johann's python node (python just makes it easier), but a lot of the infrastructure work I need to do anyways for C++ support would also be needed for the python migration, so once we can do that it should just be a few minor tweaks.

It won't be as ergonomic to use as Johann's code but hopefully it should still be straightforward to add a mapping. I also won't support responding to service requests yet, we don't have a need for it as far as I can tell and that requires more thought on how to handle the API.

This will probably be rolled into one giant PR, but this issue is mostly a place for me to just put a list of things to do.

### Tasks

- [ ] ~~ROS msg outputs for nunavut (custom templates for now, I could likely get it upstreamed in the future).~~
     - ~~This will get funky, mostly because of union types.~~
- [ ] ~~Integrate the messages and DSDL compilation into the build system.~~
- [ ] Write a simple C++ wrapper around libcanard.
- [ ] Hook in translation infrastructure so adding new mappings is simple.

**Comment by mdepp** [comment]
@davidlenfesty You probably already know this but note that some of what the mapper node did is now in [hardware.cpp](https://github.com/UofA-SPEAR/software/blob/master/spear_rover/src/hardware.cpp). In particular hardware.cpp directly publishes and subscribes to/from canros to send commands and get wheel odometry. That's a hack though and not how hardware_interface is meant to be used; it's supposed to do the low-level comm stuff itself (I don't really know anything about CAN but I'm guessing that's what the wrapper around libcanard is).

**Comment by davidlenfesty** [comment]
I did not know that. Either way this work is meant to replace canros itself, as we are migrating from UAVCAN v0 to v1 on the embedded side, and canros doesn't support v1.

Just for some extra context if you're interested:

CAN is the hardware protocol, and UAVCAN is a layer on top of it (closest analog is CAN == Ethernet and UAVCAN == TCP with some serialization semantics). UAVCAN libraries for v0 are being deprecated and aren't great to support (e.g there is no functioning DSDL C compiler, which is the equivalent to ROS msg files).

libcanard is the C library for UAVCAN. The C++ libraries and DSDL compiler are on their way but not ready yet. I would ideally be using pyuavcan, because it's more than performant enough for our case and *much* easier to implement the generic functionality I want here, but it only supports Python >= 3.6 (for v1), which is obviously out of reach until we switch to ROS 2 or Noetic. I do plan on properly re-implementing that when we switch but for now I want *something* in place in case we can make it to competitions this year.

**Comment by davidlenfesty** [comment]
ROS message generation is a lot of work and looks like it will need some upstreamed features. Currently our use case is served just as well manually writing our message types when we need to do the translation.

It's not worth the time at the current moment although it is definitely some future work. I have some starts to templating in the uavcan_dsdl repo for posterity.

**Comment by jopgen** [comment]
Closing since we are not planning on migrating to v1 anymore
